/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as OauthConsentRouteImport } from "./routes/oauth.consent";
import { Route as AuthenticatedSkillsRouteImport } from "./routes/_authenticated/skills";
import { Route as AuthenticatedSettingsRouteImport } from "./routes/_authenticated/settings";
import { Route as AuthenticatedCreateSkillRouteImport } from "./routes/_authenticated/create-skill";
import { Route as AuthenticatedAddSkillRouteImport } from "./routes/_authenticated/add-skill";
import { Route as AuthenticatedSkillsIndexRouteImport } from "./routes/_authenticated/skills.index";
import { Route as AuthenticatedSkillsSkillNameRouteImport } from "./routes/_authenticated/skills.$skillName";
import { Route as AuthenticatedSkillsSkillNameEditRouteImport } from "./routes/_authenticated/skills.$skillName.edit";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: "/oauth/consent",
  path: "/oauth/consent",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedSkillsRoute = AuthenticatedSkillsRouteImport.update({
  id: "/skills",
  path: "/skills",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedCreateSkillRoute =
  AuthenticatedCreateSkillRouteImport.update({
    id: "/create-skill",
    path: "/create-skill",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedAddSkillRoute = AuthenticatedAddSkillRouteImport.update({
  id: "/add-skill",
  path: "/add-skill",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedSkillsIndexRoute =
  AuthenticatedSkillsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedSkillsRoute,
  } as any);
const AuthenticatedSkillsSkillNameRoute =
  AuthenticatedSkillsSkillNameRouteImport.update({
    id: "/$skillName",
    path: "/$skillName",
    getParentRoute: () => AuthenticatedSkillsRoute,
  } as any);
const AuthenticatedSkillsSkillNameEditRoute =
  AuthenticatedSkillsSkillNameEditRouteImport.update({
    id: "/edit",
    path: "/edit",
    getParentRoute: () => AuthenticatedSkillsSkillNameRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/add-skill": typeof AuthenticatedAddSkillRoute;
  "/create-skill": typeof AuthenticatedCreateSkillRoute;
  "/settings": typeof AuthenticatedSettingsRoute;
  "/skills": typeof AuthenticatedSkillsRouteWithChildren;
  "/oauth/consent": typeof OauthConsentRoute;
  "/skills/$skillName": typeof AuthenticatedSkillsSkillNameRouteWithChildren;
  "/skills/": typeof AuthenticatedSkillsIndexRoute;
  "/skills/$skillName/edit": typeof AuthenticatedSkillsSkillNameEditRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/add-skill": typeof AuthenticatedAddSkillRoute;
  "/create-skill": typeof AuthenticatedCreateSkillRoute;
  "/settings": typeof AuthenticatedSettingsRoute;
  "/oauth/consent": typeof OauthConsentRoute;
  "/skills/$skillName": typeof AuthenticatedSkillsSkillNameRouteWithChildren;
  "/skills": typeof AuthenticatedSkillsIndexRoute;
  "/skills/$skillName/edit": typeof AuthenticatedSkillsSkillNameEditRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/_authenticated/add-skill": typeof AuthenticatedAddSkillRoute;
  "/_authenticated/create-skill": typeof AuthenticatedCreateSkillRoute;
  "/_authenticated/settings": typeof AuthenticatedSettingsRoute;
  "/_authenticated/skills": typeof AuthenticatedSkillsRouteWithChildren;
  "/oauth/consent": typeof OauthConsentRoute;
  "/_authenticated/skills/$skillName": typeof AuthenticatedSkillsSkillNameRouteWithChildren;
  "/_authenticated/skills/": typeof AuthenticatedSkillsIndexRoute;
  "/_authenticated/skills/$skillName/edit": typeof AuthenticatedSkillsSkillNameEditRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/add-skill"
    | "/create-skill"
    | "/settings"
    | "/skills"
    | "/oauth/consent"
    | "/skills/$skillName"
    | "/skills/"
    | "/skills/$skillName/edit";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/add-skill"
    | "/create-skill"
    | "/settings"
    | "/oauth/consent"
    | "/skills/$skillName"
    | "/skills"
    | "/skills/$skillName/edit";
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/login"
    | "/_authenticated/add-skill"
    | "/_authenticated/create-skill"
    | "/_authenticated/settings"
    | "/_authenticated/skills"
    | "/oauth/consent"
    | "/_authenticated/skills/$skillName"
    | "/_authenticated/skills/"
    | "/_authenticated/skills/$skillName/edit";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  OauthConsentRoute: typeof OauthConsentRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/oauth/consent": {
      id: "/oauth/consent";
      path: "/oauth/consent";
      fullPath: "/oauth/consent";
      preLoaderRoute: typeof OauthConsentRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/skills": {
      id: "/_authenticated/skills";
      path: "/skills";
      fullPath: "/skills";
      preLoaderRoute: typeof AuthenticatedSkillsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/settings": {
      id: "/_authenticated/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/create-skill": {
      id: "/_authenticated/create-skill";
      path: "/create-skill";
      fullPath: "/create-skill";
      preLoaderRoute: typeof AuthenticatedCreateSkillRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/add-skill": {
      id: "/_authenticated/add-skill";
      path: "/add-skill";
      fullPath: "/add-skill";
      preLoaderRoute: typeof AuthenticatedAddSkillRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/skills/": {
      id: "/_authenticated/skills/";
      path: "/";
      fullPath: "/skills/";
      preLoaderRoute: typeof AuthenticatedSkillsIndexRouteImport;
      parentRoute: typeof AuthenticatedSkillsRoute;
    };
    "/_authenticated/skills/$skillName": {
      id: "/_authenticated/skills/$skillName";
      path: "/$skillName";
      fullPath: "/skills/$skillName";
      preLoaderRoute: typeof AuthenticatedSkillsSkillNameRouteImport;
      parentRoute: typeof AuthenticatedSkillsRoute;
    };
    "/_authenticated/skills/$skillName/edit": {
      id: "/_authenticated/skills/$skillName/edit";
      path: "/edit";
      fullPath: "/skills/$skillName/edit";
      preLoaderRoute: typeof AuthenticatedSkillsSkillNameEditRouteImport;
      parentRoute: typeof AuthenticatedSkillsSkillNameRoute;
    };
  }
}

interface AuthenticatedSkillsSkillNameRouteChildren {
  AuthenticatedSkillsSkillNameEditRoute: typeof AuthenticatedSkillsSkillNameEditRoute;
}

const AuthenticatedSkillsSkillNameRouteChildren: AuthenticatedSkillsSkillNameRouteChildren =
  {
    AuthenticatedSkillsSkillNameEditRoute:
      AuthenticatedSkillsSkillNameEditRoute,
  };

const AuthenticatedSkillsSkillNameRouteWithChildren =
  AuthenticatedSkillsSkillNameRoute._addFileChildren(
    AuthenticatedSkillsSkillNameRouteChildren,
  );

interface AuthenticatedSkillsRouteChildren {
  AuthenticatedSkillsSkillNameRoute: typeof AuthenticatedSkillsSkillNameRouteWithChildren;
  AuthenticatedSkillsIndexRoute: typeof AuthenticatedSkillsIndexRoute;
}

const AuthenticatedSkillsRouteChildren: AuthenticatedSkillsRouteChildren = {
  AuthenticatedSkillsSkillNameRoute:
    AuthenticatedSkillsSkillNameRouteWithChildren,
  AuthenticatedSkillsIndexRoute: AuthenticatedSkillsIndexRoute,
};

const AuthenticatedSkillsRouteWithChildren =
  AuthenticatedSkillsRoute._addFileChildren(AuthenticatedSkillsRouteChildren);

interface AuthenticatedRouteChildren {
  AuthenticatedAddSkillRoute: typeof AuthenticatedAddSkillRoute;
  AuthenticatedCreateSkillRoute: typeof AuthenticatedCreateSkillRoute;
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute;
  AuthenticatedSkillsRoute: typeof AuthenticatedSkillsRouteWithChildren;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAddSkillRoute: AuthenticatedAddSkillRoute,
  AuthenticatedCreateSkillRoute: AuthenticatedCreateSkillRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSkillsRoute: AuthenticatedSkillsRouteWithChildren,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  OauthConsentRoute: OauthConsentRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
